### ISSUE TITLE
Add MVC Structure

### ISSUE THREAD

**Issue by varunrachakatla** [Jitender-Singh-NWM/FoodDeliveryApp-Web#1]
It would be better if you guys maintain your repo in a mvc folder structure. you can refer below link for more information
[react mvc folder structure](https://blog.webdevsimplified.com/2022-07/react-folder-structure/)

Thank you

**Comment by Jitender-Singh-NWM** [comment]
Hi The code is structured. The code base is in two folders, which is frontend and backend. Additional files were part of ad hoc assignment submissions in the past. Please consider those folders! we will be cleaning it up as we progress through the project .
